# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
