# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170729_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
