# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_details_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='tags',
            field=models.CharField(default='products', max_length=1000),
        ),
    ]
